import { test } from "node:test";
import assert from "node:assert/strict";
import { createSidecarDashboardFoundation } from "../src/catalog/sidecar-dashboard-foundation.js";

test("sidecar dashboard foundation summarizes deterministic saved sync metadata", () => {
  const foundation = createSidecarDashboardFoundation();
  const entries = [
    {
      imageId: "img-unsaved",
      updatedAt: "2025-07-20T00:00:00.000Z",
      sidecarPath: null,
    },
    {
      imageId: "img-sync",
      updatedAt: "2025-07-20T00:00:01.000Z",
      sidecarPath: "/tmp/img-sync.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:10.000Z",
    },
    {
      imageId: "img-conflict",
      updatedAt: "2025-07-20T00:00:02.000Z",
      sidecarPath: "/tmp/img-conflict.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:12.000Z",
    },
    {
      imageId: "img-missing",
      updatedAt: "2025-07-20T00:00:03.000Z",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:13.000Z",
    },
    {
      imageId: "img-sidecar-newer",
      updatedAt: "2025-07-20T00:00:04.000Z",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:14.000Z",
    },
  ];
  const syncStates = [
    {
      imageId: "img-sync",
      sidecarPath: "/tmp/img-sync.photogenic.json",
      updatedAt: "2025-07-20T00:00:01.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sync",
      sidecarFingerprint: "sidecar-sync",
      catalogRevision: 1,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-sync.photogenic.json", status: "present", byteSize: 123, modifiedAt: "2025-07-20T00:00:01.000Z" },
      revisionDrift: { status: "matched", delta: 0 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    {
      imageId: "img-conflict",
      sidecarPath: "/tmp/img-conflict.photogenic.json",
      updatedAt: "2025-07-20T00:00:02.000Z",
      status: "conflict",
      catalogFingerprint: "catalog-conflict",
      sidecarFingerprint: "sidecar-conflict",
      catalogRevision: 2,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-conflict.photogenic.json", status: "present", byteSize: 145, modifiedAt: "2025-07-20T00:00:02.000Z" },
      revisionDrift: { status: "catalog-newer", delta: 1 },
      sidecarFreshness: { status: "modified-after-link", modifiedAfterLink: true },
    },
    {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
  ];

  const summary = foundation.summarizeSavedSyncStates({ entries, syncStates });

  assert.deepEqual(summary, {
    counts: {
      totalImages: 5,
      withSavedSidecars: 4,
      withoutSavedSidecars: 1,
      withLinkedTimestamp: 4,
      withoutLinkedTimestamp: 0,
      inSync: 2,
      conflicts: 1,
      missingSidecars: 1,
      syncIssues: 2,
      withObservedSidecarFile: 3,
      withMissingObservedSidecarFile: 1,
      withMatchedRevision: 1,
      withCatalogNewerRevision: 1,
      withSidecarNewerRevision: 1,
      withUnknownRevisionDrift: 1,
      withRevisionIssue: 3,
      unchangedSinceLink: 2,
      modifiedAfterLink: 1,
      missingSinceLink: 1,
      unknownFreshness: 0,
      withFreshnessIssue: 2,
    },
    savedSidecarFiles: {
      byteSizeTotal: 428,
      withKnownByteSize: 3,
      withKnownModifiedAt: 3,
      latestModifiedAt: "2025-07-20T00:00:04.000Z",
    },
    linkedTimeline: {
      withLinkedAt: 4,
      withoutLinkedAt: 0,
      earliestLinkedAt: "2025-07-20T00:00:10.000Z",
      latestLinkedAt: "2025-07-20T00:00:14.000Z",
      spanMs: 4000,
      spanStatus: "range",
    },
    latestImageIds: ["img-sidecar-newer", "img-missing", "img-conflict", "img-sync", "img-unsaved"],
    latestLinkedImageIds: ["img-sidecar-newer", "img-missing", "img-conflict", "img-sync"],
    earliestLinkedWithTimestamp: {
      imageId: "img-sync",
      updatedAt: "2025-07-20T00:00:01.000Z",
      sidecarPath: "/tmp/img-sync.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:10.000Z",
    },
    latestLinkedWithTimestamp: {
      imageId: "img-sidecar-newer",
      updatedAt: "2025-07-20T00:00:04.000Z",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      sidecarLinkedAt: "2025-07-20T00:00:14.000Z",
    },
    latestLinkedWithoutTimestamp: null,
    latestInSync: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestMatchedRevision: {
      imageId: "img-sync",
      sidecarPath: "/tmp/img-sync.photogenic.json",
      updatedAt: "2025-07-20T00:00:01.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sync",
      sidecarFingerprint: "sidecar-sync",
      catalogRevision: 1,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-sync.photogenic.json", status: "present", byteSize: 123, modifiedAt: "2025-07-20T00:00:01.000Z" },
      revisionDrift: { status: "matched", delta: 0 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestSyncIssue: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    latestConflict: {
      imageId: "img-conflict",
      sidecarPath: "/tmp/img-conflict.photogenic.json",
      updatedAt: "2025-07-20T00:00:02.000Z",
      status: "conflict",
      catalogFingerprint: "catalog-conflict",
      sidecarFingerprint: "sidecar-conflict",
      catalogRevision: 2,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-conflict.photogenic.json", status: "present", byteSize: 145, modifiedAt: "2025-07-20T00:00:02.000Z" },
      revisionDrift: { status: "catalog-newer", delta: 1 },
      sidecarFreshness: { status: "modified-after-link", modifiedAfterLink: true },
    },
    latestMissingSidecar: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    latestObservedSidecarFile: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestMissingObservedSidecarFile: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    largestObservedSidecarFile: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestRevisionIssue: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestCatalogNewerRevision: {
      imageId: "img-conflict",
      sidecarPath: "/tmp/img-conflict.photogenic.json",
      updatedAt: "2025-07-20T00:00:02.000Z",
      status: "conflict",
      catalogFingerprint: "catalog-conflict",
      sidecarFingerprint: "sidecar-conflict",
      catalogRevision: 2,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-conflict.photogenic.json", status: "present", byteSize: 145, modifiedAt: "2025-07-20T00:00:02.000Z" },
      revisionDrift: { status: "catalog-newer", delta: 1 },
      sidecarFreshness: { status: "modified-after-link", modifiedAfterLink: true },
    },
    latestSidecarNewerRevision: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestUnknownRevisionDrift: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    latestUnchangedSinceLink: {
      imageId: "img-sidecar-newer",
      sidecarPath: "/tmp/img-sidecar-newer.photogenic.json",
      updatedAt: "2025-07-20T00:00:04.000Z",
      status: "in-sync",
      catalogFingerprint: "catalog-sidecar-newer",
      sidecarFingerprint: "catalog-sidecar-newer",
      catalogRevision: 2,
      sidecarRevision: 5,
      sidecarFile: { path: "/tmp/img-sidecar-newer.photogenic.json", status: "present", byteSize: 160, modifiedAt: "2025-07-20T00:00:04.000Z" },
      revisionDrift: { status: "sidecar-newer", delta: -3 },
      sidecarFreshness: { status: "unchanged-since-link", modifiedAfterLink: false },
    },
    latestFreshnessIssue: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    latestModifiedAfterLink: {
      imageId: "img-conflict",
      sidecarPath: "/tmp/img-conflict.photogenic.json",
      updatedAt: "2025-07-20T00:00:02.000Z",
      status: "conflict",
      catalogFingerprint: "catalog-conflict",
      sidecarFingerprint: "sidecar-conflict",
      catalogRevision: 2,
      sidecarRevision: 1,
      sidecarFile: { path: "/tmp/img-conflict.photogenic.json", status: "present", byteSize: 145, modifiedAt: "2025-07-20T00:00:02.000Z" },
      revisionDrift: { status: "catalog-newer", delta: 1 },
      sidecarFreshness: { status: "modified-after-link", modifiedAfterLink: true },
    },
    latestMissingSinceLink: {
      imageId: "img-missing",
      sidecarPath: "/tmp/img-missing.photogenic.json",
      updatedAt: "2025-07-20T00:00:03.000Z",
      status: "missing-sidecar",
      catalogFingerprint: "catalog-missing",
      sidecarFingerprint: null,
      catalogRevision: 3,
      sidecarRevision: null,
      sidecarFile: { path: "/tmp/img-missing.photogenic.json", status: "missing", byteSize: null, modifiedAt: null },
      revisionDrift: { status: "unknown", delta: null },
      sidecarFreshness: { status: "missing", modifiedAfterLink: null },
    },
    latestUnknownFreshness: null,
  });

  entries[3].imageId = "mutated";
  syncStates[2].status = "in-sync";
  assert.equal(summary.latestImageIds[0], "img-sidecar-newer");
  assert.equal(summary.latestLinkedImageIds[0], "img-sidecar-newer");
  assert.equal(summary.linkedTimeline.latestLinkedAt, "2025-07-20T00:00:14.000Z");
  assert.equal(summary.linkedTimeline.spanMs, 4000);
  assert.equal(summary.linkedTimeline.spanStatus, "range");
  assert.equal(summary.earliestLinkedWithTimestamp.imageId, "img-sync");
  assert.equal(summary.latestLinkedWithTimestamp.imageId, "img-sidecar-newer");
  assert.equal(summary.latestSyncIssue.imageId, "img-missing");
  assert.equal(summary.latestMissingSidecar.status, "missing-sidecar");
  assert.equal(summary.latestObservedSidecarFile.imageId, "img-sidecar-newer");
  assert.equal(summary.latestMissingObservedSidecarFile.imageId, "img-missing");
  assert.equal(summary.largestObservedSidecarFile.imageId, "img-sidecar-newer");
  assert.equal(summary.latestUnchangedSinceLink.imageId, "img-sidecar-newer");
  assert.equal(summary.latestFreshnessIssue.imageId, "img-missing");
  assert.equal(summary.latestMissingSinceLink.imageId, "img-missing");
  assert.equal(summary.latestMatchedRevision.imageId, "img-sync");
  assert.equal(summary.latestRevisionIssue.imageId, "img-sidecar-newer");
  assert.equal(summary.latestCatalogNewerRevision.imageId, "img-conflict");
  assert.equal(summary.latestSidecarNewerRevision.imageId, "img-sidecar-newer");
  assert.equal(summary.latestUnknownRevisionDrift.imageId, "img-missing");
});

test("sidecar dashboard foundation handles empty saved sync history", () => {
  const foundation = createSidecarDashboardFoundation();
  const summary = foundation.summarizeSavedSyncStates();

  assert.deepEqual(summary, {
    counts: {
      totalImages: 0,
      withSavedSidecars: 0,
      withoutSavedSidecars: 0,
      withLinkedTimestamp: 0,
      withoutLinkedTimestamp: 0,
      inSync: 0,
      conflicts: 0,
      missingSidecars: 0,
      syncIssues: 0,
      withObservedSidecarFile: 0,
      withMissingObservedSidecarFile: 0,
      withMatchedRevision: 0,
      withCatalogNewerRevision: 0,
      withSidecarNewerRevision: 0,
      withUnknownRevisionDrift: 0,
      withRevisionIssue: 0,
      unchangedSinceLink: 0,
      modifiedAfterLink: 0,
      missingSinceLink: 0,
      unknownFreshness: 0,
      withFreshnessIssue: 0,
    },
    savedSidecarFiles: {
      byteSizeTotal: 0,
      withKnownByteSize: 0,
      withKnownModifiedAt: 0,
      latestModifiedAt: null,
    },
    linkedTimeline: {
      withLinkedAt: 0,
      withoutLinkedAt: 0,
      earliestLinkedAt: null,
      latestLinkedAt: null,
      spanMs: null,
      spanStatus: "unknown",
    },
    latestImageIds: [],
    latestLinkedImageIds: [],
    earliestLinkedWithTimestamp: null,
    latestLinkedWithTimestamp: null,
    latestLinkedWithoutTimestamp: null,
    latestInSync: null,
    latestSyncIssue: null,
    latestMatchedRevision: null,
    latestRevisionIssue: null,
    latestConflict: null,
    latestMissingSidecar: null,
    latestObservedSidecarFile: null,
    latestMissingObservedSidecarFile: null,
    largestObservedSidecarFile: null,
    latestCatalogNewerRevision: null,
    latestSidecarNewerRevision: null,
    latestUnknownRevisionDrift: null,
    latestUnchangedSinceLink: null,
    latestFreshnessIssue: null,
    latestModifiedAfterLink: null,
    latestMissingSinceLink: null,
    latestUnknownFreshness: null,
  });
});
