
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async viewportProofResults() : Promise<ViewportProofResult[]> {
    return await TAURI_INVOKE("viewport_proof_results");
},
/**
 * Save the viewport proof report to the verification directory.
 * Called by the webview JS after collecting all gate results.
 */
async saveViewportProof(reportJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_viewport_proof", { reportJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pipelineCapabilities() : Promise<PipelineCapabilities> {
    return await TAURI_INVOKE("pipeline_capabilities");
},
async renderPipeline(request: PipelineRenderRequest) : Promise<Result<PipelineRenderResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_pipeline", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSources(request: ImportSourcesRequest) : Promise<Result<ImportSourcesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_sources", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLibrary() : Promise<Result<ImportedImageRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_library") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecipe(imageId: string) : Promise<Result<JsonValue | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recipe", { imageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRecipe(imageId: string, recipe: JsonValue, updatedAt: string | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recipe", { imageId, recipe, updatedAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPresets() : Promise<Result<PresetEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePreset(presetId: string, name: string, recipe: JsonValue) : Promise<Result<PresetEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preset", { presetId, name, recipe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Criterion 7: Apply a preset to an image with full recipe validation.
 * Returns an error if the preset recipe is structurally invalid.
 */
async applyPreset(presetId: string, targetImageId: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_preset", { presetId, targetImageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceState(workspaceId: string) : Promise<Result<WorkspaceStateEntry | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_state", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWorkspaceState(workspaceId: string, stateJson: JsonValue) : Promise<Result<WorkspaceStateEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workspace_state", { workspaceId, stateJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Criterion 8: Batch Sync — copy selected operation types from a source
 * image's recipe to all other images in the library.
 */
async batchSync(sourceImageId: string, operationTypes: string[]) : Promise<Result<BatchSyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_sync", { sourceImageId, operationTypes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Criterion 9: Check licensing state before allowing export.
 * Reads a `license.json` file from the app data directory and verifies the Ed25519 signature.
 */
async checkLicense() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_license") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Culling: update rating, flag, reject, or color label for an image.
 * Any field left as `None` is unchanged.  An empty `color_label` string
 * clears the label.
 */
async updateCulling(imageId: string, rating: number | null, flagged: boolean | null, rejected: boolean | null, colorLabel: string | null) : Promise<Result<CullingMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_culling", { imageId, rating, flagged, rejected, colorLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Culling: list all culling metadata entries.
 */
async listCulling() : Promise<Result<CullingMetadata[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_culling") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportImage(request: ExportImageRequest) : Promise<Result<ExportImageResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_image", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import source files into the managed catalog store.
 */
async importImages(sourcePaths: string[]) : Promise<Result<ImportSourcesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_images", { sourcePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BatchSyncResult = { updated_count: number; skipped_count: number; message: string }
/**
 * Culling metadata for a library image.
 * `rating` is 0-5, `flagged`/`rejected` are booleans stored as 0/1,
 * `color_label` is an optional string (e.g. "red", "blue").
 */
export type CullingMetadata = { image_id: string; rating: number; flagged: boolean; rejected: boolean; color_label: string | null; updated_at: string }
/**
 * Export: decode source → apply pipeline → encode PNG → write to file.
 * This is the real export path for Issue 13 (writes real Pipeline outputs)
 * wired from the Issue 12 export panel (criterion 9: export execution).
 */
export type ExportImageRequest = { imageId: string; sourcePath: string; recipe: JsonValue; outputPath: string; 
/**
 * Output format: "png" (default), "tiff-8", "tiff-16", or "jpeg".
 */
outputFormat?: string | null; 
/**
 * JPEG quality (1–100). Defaults to 92. Only used for JPEG format.
 */
quality?: number | null }
export type ExportImageResult = { outputPath: string; width: number; height: number; format: string; fileSizeBytes: number; recipeFingerprint: string }
export type ImportSourceEntry = { imageId: string; sourcePath: string; fileName: string; observedFormat: string; byteSize: number | null; modifiedAt: string | null }
export type ImportSourcesRequest = { databasePath: string; sourcePaths: string[] }
export type ImportSourcesResult = { imported: ImportSourceEntry[]; skipped: SkippedImportSource[] }
export type ImportedImageRow = { image_id: string; source_path: string; file_name: string; observed_format: string; byte_size: number | null; modified_at: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type PipelineCapabilities = { mode: PipelineCapabilityMode; adapterName: string | null; fallbackReason: string | null }
export type PipelineCapabilityMode = "gpuReady" | "cpuFallback"
export type PipelineRenderHash = { algorithm: string; value: string }
export type PipelineRenderMode = "preview" | "export"
export type PipelineRenderOutput = { width: number; height: number; format: string }
export type PipelineRenderRequest = { mode: PipelineRenderMode; source: PipelineRenderSource; recipe: JsonValue; output?: PipelineRenderOutput | null; width?: number; height?: number; samples?: number[] }
export type PipelineRenderResult = { mode: PipelineRenderMode; width: number; height: number; format: string; sourceIdentity: PipelineRenderSourceIdentity; recipeFingerprint: string; pixelHash: PipelineRenderHash; samples: number[] }
export type PipelineRenderSource = { imageId: string; path: string | null; revision: string | null; width: number; height: number }
export type PipelineRenderSourceIdentity = { imageId: string; path: string | null; revision: string | null }
export type PresetEntry = { preset_id: string; name: string; recipe_json: string; created_at: string; updated_at: string }
export type SkippedImportSource = { sourcePath: string; reason: string }
export type ViewportProofMetrics = { physicalWidth?: number | null; physicalHeight?: number | null; scaleFactor?: number | null; frameCount?: number | null; durationMs?: number | null; sourceFileId?: string | null; recipeFingerprint?: string | null; frameWidth?: number | null; frameHeight?: number | null; transferMethod?: string | null; frameHash?: string | null; renderDurationMs?: number | null; red?: number | null; green?: number | null; blue?: number | null; alpha?: number | null }
export type ViewportProofResult = { id: string; passed: boolean; fps?: number | null; metrics?: ViewportProofMetrics | null; note: string }
export type WorkspaceStateEntry = { workspace_id: string; state_json: string; updated_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
